### ISSUE TITLE
Error: Cannot find module '../helper-hardhat-config'

### ISSUE THREAD

**Issue by AnneCh** [wardu/planet-plots#2]
I managed to run the deploy script for the mock VRF on `hardhat`.
`deploy-test` runs both smoothly on `rinkeby` and `hardhat`.

But `deploy-mars.js` keeps failing. Several types of error messages came through, but the latest one is :
```
Error: Cannot find module '../helper-hardhat-config'
```

Before that, there's been an issue of module/export compatibility, having to do with ES6 and CommonJs (https://stackoverflow.com/questions/38296667/getting-unexpected-token-export), that I've managed to solve by adding 
```
"type": "commonjs",
```
to the `package.json`. It didn't work the first time though, and I switched to `module` (or modules, I don't recall at this exact moment), but it threw an error about `export` not being a valid keyword etc.

I tried without any `type` in the package, but ultimately, after deleting several times the `package-lock.json` adn the `node_modules` folder and running `npm install`, it came to this moment where the problem is about importing the variables from `helper-hardhat-config` in order to deploy our `MarsNFT.sol`

**Comment by AnneCh** [comment]
I've tried removing the `hardhat-toolbox` plug-in that hardhat comes in with (more details [here](https://openbase.com/js/@nomicfoundation/hardhat-toolbox), and reinstalled manually the dependencies:
```
"devDependencies": {
    "@nomiclabs/hardhat-etherscan": "^3.1.0",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "chai": "^4.3.6",
    "mocha": "^10.0.0",
    "hardhat-network-helpers": "^0.0.1"
  },
  "dependencies": {
    "@chainlink/contracts": "^0.4.1",
    "@openzeppelin/contracts": "^4.7.0",
    "dotenv": "^16.0.1",
    "fs": "^0.0.1-security",
    "hardhat-gas-reporter": "^1.0.8",
    "prettier": "^2.7.1",
    "prettier-plugin-solidity": "^1.0.0-dev.23"
  }
  ```
  
  Still, the problem persists, hardhat does not seem to be able to find the helper-hardhat-config:
  ```
  anne@AnneSager:~/planet-plots$ npx hardhat run scripts/deploy/deploy-mars.js 
Error: Cannot find module 'scripts/helper-hardhat-config.js'
Require stack:
- /home/anne/planet-plots/scripts/deploy/deploy-mars.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/anne/planet-plots/scripts/deploy/deploy-mars.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```

**Comment by AnneCh** [comment]
I've looked at other examples using other configuration files than just the normal `hardhat-config`, but I cannot find an example that has the exact same characteristics (use of JavaScript and not TypeScript, use of the boilerplate and the `toolbox` and not using `hardhat-deploy`..)

My next test is to try to circumvent the use of the helper's script, see if I can put that data somewhere else  that hardhat would be pleased with.

**Comment by AnneCh** [comment]
I've tried integrating the data from `helper-hardhat-config.js` into `hardhat.config.js` but it totally failed.

Funny thing though, after I re instated the original `helper-hardhat-config.js`, I observed that it's `hardhat.config.js`, and not `hardhat-config.js`. So I tried modifying it into `helper-hardhat.config.js`.

Now the deploy script starts running, but it returns `undefined` for the values hardcoded into `helper`, thus providing only 2 of the 5 arguments passed into the constructor:
```
anne@AnneSager:~/planet-plots$ npx hardhat run scripts/deploy/deploy-mars.js 
The Hardhat Network tracing engine could not be initialized. Run Hardhat with --verbose to learn more.
1337
Deploying the contracts with the account: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
You are using hardhat's network, you need Mocks. Deploying them for you...
Mocks Deployed!
---------------------------------------------
You are deploying to a local network, you'll need a local network running to interact
Please run `npx hardhat console --network localhost` to interact with the deployed smart contracts!
---------------------------------------------
0x5FbDB2315678afecb367f032d93F642f64180aa3
Mocks funded
Error: missing argument:  in Contract constructor **(count=2, expectedCount=5,** code=MISSING_ARGUMENT, version=contracts/5.6.2)
    at Logger.makeError (/home/anne/planet-plots/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/home/anne/planet-plots/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Logger.checkArgumentCount (/home/anne/planet-plots/node_modules/@ethersproject/logger/src.ts/index.ts:332:18)
    at ContractFactory.<anonymous> (/home/anne/planet-plots/node_modules/@ethersproject/contracts/src.ts/index.ts:1237:16)
    at step (/home/anne/planet-plots/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/home/anne/planet-plots/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at /home/anne/planet-plots/node_modules/@ethersproject/contracts/lib/index.js:23:71
    at new Promise (<anonymous>)
    at __awaiter (/home/anne/planet-plots/node_modules/@ethersproject/contracts/lib/index.js:19:12)
    at ContractFactory.deploy (/home/anne/planet-plots/node_modules/@ethersproject/contracts/lib/index.js:1138:16) {
  reason: 'missing argument:  in Contract constructor',
  code: 'MISSING_ARGUMENT',
  count: 2,
  expectedCount: 5
}
```

**Comment by AnneCh** [comment]
trying to deploy on `rinkeby` does the same it returns `vrfCoordinatorV2` as `undefined`

**Comment by AnneCh** [comment]
I think the problems comes from the syntax of those lines (and similar lines above in the code)
```
        networkConfig[chainId].gasLane, 
        networkConfig[chainId].mintFee,
        networkConfig[chainId].callbackGasLimit,
```
I've tried replacing the brackets with dots, with curly brackets, with (),  adding `network` in front of `networkConfig`, renaming the latter from the original file .... nothing works. `chainId` is already defined, it should grab whatever network id (4 or 1337) and return tthe corresponding `gasLane/mintFee/casllbackGasLimit`, but it does not.

**Comment by AnneCh** [comment]
> someone suggested renaming the `helper` config file with `cjs` extension instead of `js`, but still does not work

same for the extension `.mjs`

**Comment by AnneCh** [comment]
The problem was not coming from the module VS commonjs,  or the import of the `helper-hardhat-config`, but instead it was the syntax inside the constructor parameters. 
Not using the `hardhat-deploy` plugin, the syntax must then be :
```
   const marsToken = await marsFactory.deploy(
        vrfCoordinatorV2Address,
        subscriptionId,
        networkConfig[chainId].gasLane,
        networkConfig[chainId].mintFee,
        networkConfig[chainId].callbackGasLimit
    )
```

and I was able to deploy successfully on hardhat and Rinkeby - although the verify() is not working, I need to work on that
